version: 2
jobs:
  build:
    branches:
      only:
        - master
    docker:
      - image: deptno/circleci-awscli-node8:0.1
    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
          - yarn-packages-{{ checksum "yarn.lock" }}
      - restore_cache:
          key: v1-npm-deps-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - run:
          name: Check typescript compilation
          command: yarn type-check
      - run:
          name: Check linter
          command: yarn lint
      - run:
          name: Run tests
          command: yarn test
      - save_cache:
        name: Save Yarn Package Cache
        key: yarn-packages-{{ checksum "yarn.lock" }}
        paths:
          - ~/.cache/yarn
