version: 2.1
orbs:
  codecov: codecov/codecov@1.0.3
  percy: percy/agent@0.1.3
jobs:
  build:
    docker:
      - image: circleci/node:11.8.0
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
          - yarn-packages-{{ checksum "yarn.lock" }}
      - restore_cache:
          key: v1-npm-deps-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - attach_workspace:
          at: .
  lint:
    docker:
      - image: circleci/node:11.8.0
    steps:
      - run:
          name: Check typescript compilation
          command: yarn type-check
      - run:
          name: Check linter
          command: yarn lint
  test:
    docker:
      - image: circleci/node:11.8.0
    steps:
      - run:
          name: Run tests with JUnit as reporter
          command: yarn test:coverage
      - store_test_results:
          path: coverage
      - store_artifacts:
          path: coverage
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - codecov/upload:
          file: coverage

workflows:
  build_and_test:
    jobs:
      - build
      - lint:
          requires:
            - build
      - test:
          requires:
            - lint
      - percy/finalize_all:
          requires:
            - test
