defaults: &defaults
  docker:
    - image: circleci/node:11.10.0
  working_directory: ~/repo
version: 2.1
orbs:
  percy: percy/agent@0.1.3
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
          - yarn-packages-{{ checksum "yarn.lock" }}
      - restore_cache:
          key: v1-npm-deps-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - persist_to_workspace:
          root: /home/circleci
          paths:
            - repo
  lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /home/circleci
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - run:
          name: Check typescript compilation
          command: yarn type-check
      - run:
          name: Check linter
          command: yarn lint
  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /home/circleci
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - run:
          name: Run tests with JUnit as reporter
          command: yarn test:coverage
      - store_test_results:
          path: coverage
      - store_artifacts:
          path: coverage
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

workflows:
  build_and_test:
    jobs:
      - build
      - lint:
          requires:
            - build
      - test:
          requires:
            - lint
      - percy/finalize_all:
          requires:
            - test
